#!/bin/bash
#Tool = ADB_ToolsDia v2
#Author = Alvaro Alonso
#Date = 2022

if [ -d $PWD/device-pull/ ]
    then
        echo -e "\e[92mDirectorio $PWD/device-pull/ ya existe \n"
    else
        mkdir $PWD/device-pull > /dev/null 2&>1
fi

adb devices | sed -n '2,$p' | awk '{ print $1 }' > .temp/dev_list_temp  2> /dev/null
dev=(`cat .temp/dev_list_temp`)
dev=("${dev[@]}")
dev_1=$(echo "${dev[0]}")
dev_2=$(echo "${dev[1]}")
dev_3=$(echo "${dev[2]}")


adb devices -l | grep model > .temp/dev_list_model_temp  2> /dev/null
model=(`cat .temp/dev_list_model_temp`)
model=("${model[@]}")
mod_1=$(echo "${model[4]}" | cut -c 7- )
mod_2=$(echo "${model[11]}" | cut -c 7- )
mod_3=$(echo "${model[18]}" | cut -c 7- )

if [ "$dev_1" == "" ]
    then
        total_dev=0
    else
        total_dev=1
        if [ "$dev_2" == "" ]
            then
                total_dev=1
            else
                total_dev=2
                if [ "$dev_3" == "" ]
                    then
                        total_dev=2
                    else
                        total_dev=3
                fi
        fi        
fi

dia_tree(){

                    echo -e "\n\e[1;93mCreando arbol de carpetas en dispositivo\n\e[93m"
                      adb shell mkdir /sdcard/dia >/dev/null
                      adb shell mkdir /sdcard/dia/history >/dev/null
                      adb shell mkdir /sdcard/dia/in >/dev/null
                      adb shell mkdir /sdcard/dia/out >/dev/null
                      adb shell mkdir /sdcard/dia/temp >/dev/null
                    echo -e "\n\e[1;92mProceso correcto\n\e[93m"

}

dev_1_dia (){
            
            echo -e "\n\e[1;92mBorrando carpetas dia en dispositvo $mod_1\n"
            adb shell rm -rR /sdcard/Dia* >/dev/null
            adb shell rm -rR /sdcard/dia* >/dev/null
            read -p $'\n\e[93;1mQuieres crear el arbol de carpetas APP DIA GT \e[1;97m (y/N) \e[93;1m? : \e[1;91m' yn
            case $yn in
                [Yy]* ) dia_tree;;
                [Nn]* ) 
                        read -p $'\n\e[93;1mDESEAS LIMPIAR LA PANTALLA (clear) \e[1;97m (y/N) \e[93;1m? : \e[1;91m' yn
                        case $yn in
                        [Yy]* ) clear; bash modulos/funcion.sh;;
                        [Nn]* ) bash modulos/funcion.sh;;
                        * ) bash modulos/funcion.sh;;
                        esac
                ;;
                * ) echo -e "\n\e[1;4;91mYy/Nn :- (1/2)\n";;
            esac


}

dev_2_dia (){

            echo -e "\n\e[1;92mBorrando carpetas dia en dispositvo $mod_2\n"
            adb shell rm -rR /sdcard/Dia* >/dev/null
            adb shell rm -rR /sdcard/dia* >/dev/null

}

dev_3_dia (){

            echo -e "\n\e[1;92mBorrando carpetas dia en dispositvo $mod_2\n"
            adb shell rm -rR /sdcard/Dia* >/dev/null
            adb shell rm -rR /sdcard/dia* >/dev/null

}

if [ "$total_dev" ==  "0" ]
    then
        echo -e "\e[91;1mNO SE HAN ENCONTRADO DISPOSITIVOS"
    else
        if [ "$total_dev" == "1" ]
            then
                echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
                dev_1_dia

            else
                if [ "$total_dev" == "2" ]
                    then
                        echo -e "\e[93mSelecciona dispositivo para abrir terminal :- \e[92m\n"
                        echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
                        echo -e "\e[93m2. \e[92m$dev_2 , \e[93mModel : \e[92m$mod_2"
                        while [ 1 ]; do
                            read -p $'\n\e[1;4;91mSelecciona\e[0m\e[24;1;97m : ' options
                            case $options in
                            "1") dev_1_dia; break;;
                            "2") dev_2_dia; break;;
                              *) echo -e "\n\e[1;4;91mEscoge un dispositivo :- (1/2)\n";;
                            esac
                        done
                    else
                        if [ "$total_dev" == "3" ]
                            then
                                echo -e "\e[93mSelecciona dispositivo para abrir terminal :- \e[92m\n"
                                echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
                                echo -e "\e[93m1. \e[92m$dev_2 , \e[93mModel : \e[92m$mod_2"
                                echo -e "\e[93m1. \e[92m$dev_3 , \e[93mModel : \e[92m$mod_3"
                        while [ 1 ]; do
                            read -p $'\n\e[1;4;91mSelecciona\e[0m\e[24;1;97m : ' options
                            case $options in
                            "1") dev_1_dia; break;;
                            "2") dev_2_dia; break;;
                            "3") dev_3_dia; break;;
                              *) echo -e "\n\e[1;4;91mEscoge un dispositivo :- (1/2/3/)\n";;
                            esac
                        done
                        fi
                fi  
                        
        fi
fi

read -p $'\n\e[93;1mDESEAS LIMPIAR LA PANTALLA (clear) \e[1;97m (y/N) \e[93;1m? : \e[1;91m' yn
case $yn in
  [Yy]* ) clear; bash modulos/funcion.sh;;
  [Nn]* ) bash modulos/funcion.sh;;
  * ) bash modulos/funcion.sh;;
esac