#!/bin/bash
#Tool = ADB_ToolsDia v2
#Author = Alvaro Alonso
#Date = 2022

if [ -d $PWD/device-pull/ ]
    then
        echo -e "\e[92mDirectorio $PWD/device-pull/ ya existe \n"
    else
        mkdir $PWD/device-pull > /dev/null 2&>1
fi

adb devices | sed -n '2,$p' | awk '{ print $1 }' > .temp/dev_list_temp  2> /dev/null
dev=(`cat .temp/dev_list_temp`)
dev=("${dev[@]}")
dev_1=$(echo "${dev[0]}")
dev_2=$(echo "${dev[1]}")
dev_3=$(echo "${dev[2]}")


adb devices -l | grep model > .temp/dev_list_model_temp  2> /dev/null
model=(`cat .temp/dev_list_model_temp`)
model=("${model[@]}")
mod_1=$(echo "${model[4]}" | cut -c 7- )
mod_2=$(echo "${model[11]}" | cut -c 7- )
mod_3=$(echo "${model[18]}" | cut -c 7- )

if [ "$dev_1" == "" ]
    then
        total_dev=0
    else
        total_dev=1
        if [ "$dev_2" == "" ]
            then
                total_dev=1
            else
                total_dev=2
                if [ "$dev_3" == "" ]
                    then
                        total_dev=2
                    else
                        total_dev=3
                fi
        fi        
fi

subida_hsr () {

                time=$(date '+%Y-%m-%d')
                read -p $'\e[1;91mEscribe un nombre para el archivo\e[0m \e[24;1;97m : ' gzname
                if [ "$gzname" = "" ]
                then
                    echo -e "Escribe un nombre por favor"
                    subida_hsr
                else
                            pushd $PWD/device-pull/$mod_1-$dev_1/ >/dev/null
                            TDA=$(cat /usr/local/n2a/etc/todasjuntas.properties | grep 'site'  | tail -n 1 | cut -d '=' -f2-)

                            tar -zcvf $gzname-$time.tar.gz dia* >/dev/null
                            echo -e "\n\e[1;93mGuardando ficheros TDA.$TDA en BBDD_HSR\n\e[93m"
                            rsync --progress $TDA-$gzname-dia-$time.tar.gz soporte@10.208.162.6:/home/BBDD_Tiendas/
                            popd >/dev/null
                    fi
}


dev_1_dia_pull () {

                echo -e "\n\e[1;93mCopiando carpeta dia del dispositivo $mod_1\n\e[93m"
                    
                    if [ -d $PWD/device-pull/"$mod_1"-"$dev_1"/ ]
                        then
                            echo -e "\e[92mDirectorio $PWD/device-pull/"$mod_1"-"$dev_1"/ ya existe. \n"
                        else
                            tmp_dir=$(echo $PWD/device-pull/$mod_1-$dev_1)
                            echo $tem_dir
                            mkdir -p $tmp_dir
                    fi
                time=$(date '+%Y-%m-%d')
                adb -s $dev_1 pull /sdcard/dia/ $PWD/device-pull/$mod_1-$dev_1/dia-$time/

                read -p $'\n\e[93;1mDESEAS SUBIR LA CARPETA DIA A HSR \e[1;97m (y/N) \e[93;1m? : \e[1;91m' yn
                case $yn in
                [Yy]* ) subida_hsr;;
                [Nn]* ) bash modulos/funcion.sh;;
                * ) echo -e "\n\e[1;4;91mYy/Nn :- (1/2)\n";;

                esac

                echo -e "\n\e[1;92mProceso completado.\n"

}

dev_2_dia_pull () {

                echo -e "\n\e[1;93mCopiando carpeta dia del dispositivo $mod_2\n\e[93m"
                    
                    if [ -d $PWD/device-pull/"$mod_2"-"$dev_2"/ ]
                        then
                            echo -e "\e[92mDirectorio $PWD/device-pull/"$mod_2"-"$dev_2"/ ya existe. \n"
                        else
                            tmp_dir=$(echo $PWD/device-pull/$mod_2-$dev_2)
                            echo $tem_dir
                            mkdir -p $tmp_dir
                    fi
                time=$(date '+%Y-%m-%d')
                adb -s $dev_2 pull /sdcard/dia/ $PWD/device-pull/$mod_2-$dev_2/dia-$time/

                read -p $'\n\e[93;1mDESEAS SUBIR LA CARPETA DIA A HSR \e[1;97m (y/N) \e[93;1m? : \e[1;91m' yn
                case $yn in
                [Yy]* ) subida_hsr;;
                [Nn]* ) bash modulos/funcion.sh;;
                * ) echo -e "\n\e[1;4;91mYy/Nn :- (1/2)\n";;

                esac

                echo -e "\n\e[1;92mProceso completado.\n"
}

dev_3_dia_pull () {

                echo -e "\n\e[1;93mCopiando carpeta dia del dispositivo $mod_3\n\e[93m"
                    
                    if [ -d $PWD/device-pull/"$mod_3"-"$dev_3"/ ]
                        then
                            echo -e "\e[92mDirectorio $PWD/device-pull/"$mod_3"-"$dev_3"/ ya existe. \n"
                        else
                            tmp_dir=$(echo $PWD/device-pull/$mod_3-$dev_3)
                            echo $tem_dir
                            mkdir -p $tmp_dir
                    fi
                time=$(date '+%Y-%m-%d')
                adb -s $dev_3 pull /sdcard/dia/ $PWD/device-pull/$mod_3-$dev_3/dia-$time/

                read -p $'\n\e[93;1mDESEAS SUBIR LA CARPETA DIA A HSR \e[1;97m (y/N) \e[93;1m? : \e[1;91m' yn
                case $yn in
                [Yy]* ) subida_hsr;;
                [Nn]* ) bash modulos/funcion.sh;;
                * ) echo -e "\n\e[1;4;91mYy/Nn :- (1/2)\n";;

                esac

                echo -e "\n\e[1;92mProceso completado.\n"
}

if [ "$total_dev" ==  "0" ]
    then
        echo -e "\e[91;1mNO SE HAN ENCONTRADO DISPOSITVOS"
    else
        if [ "$total_dev" == "1" ]
            then
                dev_1_dia_pull
            else
                if [ "$total_dev" == "2" ]
                    then
                        echo -e "\e[93mSelecciona el dispositivo del que quieres copiar dia :- \e[92m\n"
                        echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
                        echo -e "\e[93m2. \e[92m$dev_2 , \e[93mModel : \e[92m$mod_2"
                        while [ 1 ]; do
                            read -p $'\n\e[1;4;91mNº\e[0m\e[24;1;97m : ' options
                            case $options in
                            "1") dev_1_dia_pull; break;;
                            "2") dev_2_dia_pull; break;;
                              *) echo -e "\n\e[1;4;91mNº :- (1/2)\n";;
                            esac
                        done
                    else
                        if [ "$total_dev" == "3" ]
                            then
                                echo -e "\e[93mSelecciona el dispositivo del que quieres copiar dia :- \e[92m\n"
                                echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
                                echo -e "\e[93m1. \e[92m$dev_2 , \e[93mModel : \e[92m$mod_2"
                                echo -e "\e[93m1. \e[92m$dev_3 , \e[93mModel : \e[92m$mod_3"
                        while [ 1 ]; do
                            read -p $'\n\e[1;4;91mNº\e[0m\e[24;1;97m : ' options
                            case $options in
                            "1") dev_1_dia_pull; break;;
                            "2") dev_2_dia_pull; break;;
                            "3") dev_3_dia_pull; break;;
                              *) echo -e "\n\e[1;4;91mNº :- (1/2/3/)\n";;
                            esac
                        done
                        fi
                fi  
                        
        fi
fi

read -p $'\n\e[93;1mDESEAS LIMPIAR LA PANTALLA (clear) \e[1;97m (y/N) \e[93;1m? : \e[1;91m' yn
case $yn in
  [Yy]* ) clear; bash modulos/funcion.sh;;
  [Nn]* ) bash modulos/funcion.sh;;
  * ) bash modulos/funcion.sh;;
esac