#!/bin/bash
#Tool = ADB_ToolsDia v2
#Author = Alvaro Alonso
#Date = 2022

time=$(date +"%T")

adb devices | sed -n '2,$p' | awk '{ print $1 }' > .temp/dev_list_temp 2> /dev/null
dev=(`cat .temp/dev_list_temp`)
dev=("${dev[@]}")
dev_1=$(echo "${dev[0]}")
dev_2=$(echo "${dev[1]}")
dev_3=$(echo "${dev[2]}")


adb devices -l | grep model > .temp/dev_list_model_temp 2> /dev/null
model=(`cat .temp/dev_list_model_temp`)
model=("${model[@]}")
mod_1=$(echo "${model[4]}" | cut -c 7- )
mod_2=$(echo "${model[11]}" | cut -c 7- )
mod_3=$(echo "${model[18]}" | cut -c 7- )

if [ -d $PWD/device-pull/ ]
    then
        echo -e "\e[92mDirectorio $PWD/device-pull/ ya existe \n"
    else
        mkdir $PWD/device-pull > /dev/null 2&>1
fi

if [ "$dev_1" == "" ]
    then
        total_dev=0
    else
        total_dev=1
        if [ "$dev_2" == "" ]
            then
                total_dev=1
            else
                total_dev=2
                if [ "$dev_3" == "" ]
                    then
                        total_dev=2
                    else
                        total_dev=3
                fi
        fi        
fi

dev_record () {

                if [ -d $PWD/device-pull/$mod_1-$dev_1/capturas/ ]
                        then
                            echo -e "\e[92mDirectorio $PWD/device-pull/"$mod_1"-"$dev_1"/ ya existe. \n"

                        else
                            tmp_dir=$(echo $PWD/device-pull/$mod_1-$dev_1/capturas/)
                            echo $tem_dir
                            mkdir -p $tmp_dir
                    fi
                echo -e "\n\e[1;92mGRABANDO LA PANTALLA DE $mod_1\n"
                sudo adb shell screenrecord --bit-rate 6000000 /sdcard/screenrecord-$mod_1-$dev_1.mp4 &
                PID=$!
                read -p "Pulsa [Enter] para parar la grabación"
                kill $PID
                echo -e "\n\e[1;92mGuardando la grabación de $mod_1-$dev_1\n"
                sleep 1                 
                adb -s $dev_1 pull /sdcard/screenrecord-$mod_1-$dev_1.mp4 $PWD/device-pull/$mod_1-$dev_1/capturas/
                echo -e "\n\e[1;92mProceso completado."
                echo -e "\n\e[1;92mBorrando datos en dispositivo"
                adb shell rm /sdcard/screenrecord-$mod_1-$dev_1.mp4
                echo -e "\n\e[1;92mProceso completado."

}


dev_screenshot () {

                if [ -d $PWD/device-pull/"$mod_1"-"$dev_1"/capturas-$time/ ]
                        then
                            echo -e "\e[92mDirectorio $PWD/device-pull/"$mod_1"-"$dev_1"/ ya existe. \n"

                        else
                            tmp_dir=$(echo $PWD/device-pull/$mod_1-$dev_1/capturas-$time/)
                            echo $tem_dir
                            mkdir -p $tmp_dir
                    fi
                echo -e "\n\e[1;92mGRABANDO LA PANTALLA DE $mod_1\n"
                echo -e "\n\e[1;92mCtrl + C para salir\n"
                sudo adb shell screencap -p /sdcard/screenshot-$time.png
                PID=$!
                echo -e "\n\e[1;92mGuardando la captura de $mod_1-$dev_1\n"  
                adb -s $dev_1 pull /sdcard/$dev_screenshot $PWD/device-pull/$mod_1-$dev_1/capturas-$time/
                echo -e "\n\e[1;92mProceso completado.\n" 

}

dev_1_custom_pull () {
                
                devvv=$(echo $dev_1)
                echo -e "\e[93m1. \e[92mINICIA GRABACION DE PANTALLA"
                echo -e "\e[93m2. \e[92mTOMA UNA CAPTURA DE PANTALLA"                
                while [ 1 ]
                    do
                         read -p $'\n\e[1;4;91mNº\e[0m\e[24;1;97m : ' options
                         case $options in
                         "1") dev_record;;
                         "2") dev_screenshot;;
                         *) echo -e "\n\e[1;4;91mNº:- (1/2)\n";;
                         esac    
                done

}

dev_2_custom_pull () {
                
                devvv=$(echo $dev_1)
                echo -e "\e[93m1. \e[92mINICIA GRABACION DE PANTALLA"
                echo -e "\e[93m2. \e[92mTOMA UNA CAPTURA DE PANTALLA"                
                while [ 1 ]
                    do
                         read -p $'\n\e[1;4;91mNº\e[0m\e[24;1;97m : ' options
                         case $options in
                         "1") dev_record;;
                         "2") dev_screenshot;;
                         "0") bash modulos/funcion.sh;;
                         *) echo -e "\n\e[1;4;91mNº :- (1/2)\n";;
                         esac    
                done

}

dev_3_custom_pull () {
                
                devvv=$(echo $dev_1)
                echo -e "\e[93m1. \e[92mINICIA GRABACION DE PANTALLA"
                echo -e "\e[93m2. \e[92mTOMA UNA CAPTURA DE PANTALLA"                
                while [ 1 ]
                    do
                         read -p $'\n\e[1;4;91mNº\e[0m\e[24;1;97m : ' options
                         case $options in
                         "1") dev_record;;
                         "2") dev_screenshot;;
                         *) echo -e "\n\e[1;4;91mNº o [0] para salir :- (1/2)\n";;
                         esac
                    break    
                done

}


if [ "$total_dev" ==  "0" ]
    then
        echo -e "\e[91;1mNO SE HAN ENCONTRADO DISPOSITVOS"
    else
        if [ "$total_dev" == "1" ]
            then
                dev_1_custom_pull; break;;
            else
                if [ "$total_dev" == "2" ]
                    then
                        echo -e "\e[93mSelecciona el dispositvo :- \e[92m\n"
                        echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
                        echo -e "\e[93m2. \e[92m$dev_2 , \e[93mModel : \e[92m$mod_2"
                        while [ 1 ]; do
                            read -p $'\n\e[1;4;91mNº\e[0m\e[24;1;97m : ' options
                            case $options in
                            "1") dev_1_custom_pull; break;;
                            "2") dev_2_custom_pull; break;;
                              *) echo -e "\n\e[1;4;91mNº :- (1/2)\n";;
                            esac
                        done
                    else
                        if [ "$total_dev" == "3" ]
                            then
                                echo -e "\e[93mSelecciona el dispositvo :- \e[92m\n"
                                echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
                                echo -e "\e[93m1. \e[92m$dev_2 , \e[93mModel : \e[92m$mod_2"
                                echo -e "\e[93m1. \e[92m$dev_3 , \e[93mModel : \e[92m$mod_3"
                        while [ 1 ]; do
                            read -p $'\n\e[1;4;91mNº\e[0m\e[24;1;97m : ' options
                            case $options in
                            "1") dev_1_custom_pull; break;;
                            "2") dev_2_custom_pull; break;;
                            "3") dev_3_custom_pull; break;;
                              *) echo -e "\n\e[1;4;91mNº :- (1/2/3/)\n";;
                            esac
                        done
                        fi
                fi  
                        
        fi
fi

read -p $'\n\e[93;1mDESEAS LIMPIAR LA PANTALLA (clear) \e[1;97m (y/N) \e[93;1m? : \e[1;91m' yn
case $yn in
  [Yy]* ) clear; bash modulos/funcion.sh;;
  [Nn]* ) bash modulos/funcion.sh;;
  * ) bash modulos/funcion.sh;;
esac