#!/bin/bash
#Tool = ADB_ToolsDia v2
#Author = Alvaro Alonso
#Date = 2022

#!/bin/bash

adb devices | sed -n '2,$p' | awk '{ print $1 }' > .temp/dev_list_temp 2> /dev/null
dev=(`cat .temp/dev_list_temp`)
dev=("${dev[@]}")
dev_1=$(echo "${dev[0]}")
dev_2=$(echo "${dev[1]}")
dev_3=$(echo "${dev[2]}")

adb devices -l | grep model > .temp/dev_list_model_temp 2> /dev/null
model=(`cat .temp/dev_list_model_temp`)
model=("${model[@]}")
mod_1=$(echo "${model[4]}" | cut -c 7- )
mod_2=$(echo "${model[11]}" | cut -c 7- )
mod_3=$(echo "${model[18]}" | cut -c 7- )


if [ "$dev_1" == "" ]
    then
        total_dev=0
    else
        total_dev=1
        if [ "$dev_2" == "" ]
            then
                total_dev=1
            else
                total_dev=2
                if [ "$dev_3" == "" ]
                    then
                        total_dev=2
                    else
                        total_dev=3
                fi
        fi        
fi

dev_1_dump () {

                time=$(date +"%T")
                echo -e "\n\e[1;92mVolcando información del disposivo $mod_1\n"
                echo -e "Modelo:"  2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb shell getprop ro.product.model 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                echo -e "Marca:" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb shell getprop | grep "ro.product.manufacturer" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                echo -e "SN:" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb get-serialno 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                echo -e "VERSION_ANDROID:" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb shell getprop ro.build.version.release 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                echo -e "ANDROID_ID:" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb shell settings get secure android_id 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                echo -e "VERSION_APP_GT:" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb shell dumpsys package com.dia.tiendas.gestiontienda | grep "versionName" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &

                sleep 2.5s | echo -e "INICIANDO DISPOSITIVO, ESPERA" 
                cat sys-dump-info/$mod_1-$time-symple.dump

}

dev_2_dump () {

                time=$(date +"%T")
                echo -e "\n\e[1;92mVolcando información del disposivo $mod_1\n"
                echo -e "Modelo:"  2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb shell getprop ro.product.model 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                echo -e "Marca:" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb shell getprop | grep "ro.product.manufacturer" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                echo -e "SN:" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb get-serialno 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                echo -e "VERSION_ANDROID:" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb shell getprop ro.build.version.release 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                echo -e "ANDROID_ID:" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb shell settings get secure android_id 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                echo -e "VERSION_APP_GT:" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb shell dumpsys package com.dia.tiendas.gestiontienda | grep "versionName" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &

                sleep 2.5s | echo -e "INICIANDO DISPOSITIVO, ESPERA" 
                cat sys-dump-info/$mod_1-$time-symple.dump                
}

dev_3_dump () {

                time=$(date +"%T")
                echo -e "\n\e[1;92mVolcando información del disposivo $mod_1\n"
                echo -e "Modelo:"  2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb shell getprop ro.product.model 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                echo -e "Marca:" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb shell getprop | grep "ro.product.manufacturer" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                echo -e "SN:" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb get-serialno 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                echo -e "VERSION_ANDROID:" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb shell getprop ro.build.version.release 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                echo -e "ANDROID_ID:" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb shell settings get secure android_id 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                echo -e "VERSION_APP_GT:" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &
                adb shell dumpsys package com.dia.tiendas.gestiontienda | grep "versionName" 2> /dev/null > sys-dump-info/$mod_1-$time-symple.dump &

                sleep 2.5s | echo -e "INICIANDO DISPOSITIVO, ESPERA" 
                cat sys-dump-info/$mod_1-$time-symple.dump                
}

if [ "$total_dev" ==  "0" ]
    then
        echo -e "\e[91;1mNO SE HAN ENCONTRADO DISPOSITIVOS"
    else
        if [ "$total_dev" == "1" ]
            then
                echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
                dev_1_dump

            else
                if [ "$total_dev" == "2" ]
                    then
                        echo -e "\e[93mSelecciona el dispositivo :- \e[92m\n"
                        echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
                        echo -e "\e[93m2. \e[92m$dev_2 , \e[93mModel : \e[92m$mod_2"
                        while [ 1 ]; do
                            read -p $'\n\e[1;4;91mNº\e[0m\e[24;1;97m : ' options
                            case $options in
                            "1") dev_1_dump; break;;
                            "2") dev_2_dump; break;;
                              *) echo -e "\n\e[1;4;91mESCOGE LA OPCION CORRECTA :- (1/2)\n";;
                            esac
                        done
                    else
                        if [ "$total_dev" == "3" ]
                            then
                                echo -e "\e[93mSelecciona el dispositivo :- \e[92m\n"
                                echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
                                echo -e "\e[93m1. \e[92m$dev_2 , \e[93mModel : \e[92m$mod_2"
                                echo -e "\e[93m1. \e[92m$dev_3 , \e[93mModel : \e[92m$mod_3"
                        while [ 1 ]; do
                            read -p $'\n\e[1;4;91mNº\e[0m\e[24;1;97m : ' options
                            case $options in
                            "1") dev_1_dump; break;;
                            "2") dev_2_dump; break;;
                            "3") dev_3_dump; break;;
                              *) echo -e "\n\e[1;4;91mESCOGE LA OPCION CORRECTA :- (1/2/3/)\n";;
                            esac
                        done
                        fi
                fi  
                        
        fi
fi

read -p $'\n\e[93;1mDESEAS LIMPIAR LA PANTALLA (clear) \e[1;97m (y/N) \e[93;1m? : \e[1;91m' yn
case $yn in
  [Yy]* ) clear; bash modulos/funcion.sh;;
  [Nn]* ) bash modulos/funcion.sh;;
  * ) bash modulos/funcion.sh;;
esac