#!/bin/bash
#Tool = ADB_ToolsDia v2
#Author = Alvaro Alonso
#Date = 2022

#!/bin/bash


if [ -d $PWD/bug-report/ ]
    then
        echo
    else
        mkdir $PWD/bug-report > /dev/null 2&>1
fi

adb devices | sed -n '2,$p' | awk '{ print $1 }' > .temp/dev_list_temp 2> /dev/null
dev=(`cat .temp/dev_list_temp`)
dev=("${dev[@]}")
dev_1=$(echo "${dev[0]}")
dev_2=$(echo "${dev[1]}")
dev_3=$(echo "${dev[2]}")


adb devices -l | grep model > .temp/dev_list_model_temp 2> /dev/null
model=(`cat .temp/dev_list_model_temp`)
model=("${model[@]}")
mod_1=$(echo "${model[4]}" | cut -c 7- )
mod_2=$(echo "${model[11]}" | cut -c 7- )
mod_3=$(echo "${model[18]}" | cut -c 7- )


if [ "$dev_1" == "" ]
    then
        total_dev=0
    else
        total_dev=1
        if [ "$dev_2" == "" ]
            then
                total_dev=1
            else
                total_dev=2
                if [ "$dev_3" == "" ]
                    then
                        total_dev=2
                    else
                        total_dev=3
                fi
        fi        
fi

if [ "$total_dev" ==  "0" ]
    then
        echo -e "\e[91;1mNO SE HAN ENCONTRADO DISPOSITIVOS"
    else
        if [ "$total_dev" == "1" ]
            then
                echo -e "\n\e[1;92mLista de todos los paquetes instalados en el dispositivo  : $mod_1\n"
                echo -e "\e[1;92mPresiona q para salir de la vista\n"
                sleep 1s | echo -e "INICIANDO DISPOSITIVO, ESPERA"                 
                adb -s $dev_1  shell 'pm list packages -f' | sed -e 's/.*=//' | sed -e 's/^/ /' | sort | less
                echo -e "\n\e[1;92mLISTO"
            else
                if [ "$total_dev" == "2" ]
                    then
                        echo -e "\e[93mSelecciona un dispositivo :- \e[92m\n"
                        echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
                        echo -e "\e[93m2. \e[92m$dev_2 , \e[93mModel : \e[92m$mod_2"
                        while [ 1 ]; do
                            read -p $'\n\e[1;4;91mNº\e[0m\e[24;1;97m : ' options
                            case $options in
                            "1")  echo -e "\n\e[1;92mLista de todos los paquetes instalados en el dispositivo  : $mod_1\n"; echo -e "\e[1;92mPresiona q para salir de la vista\n"; sleep 1s | echo -e "INICIANDO DISPOSITIVO, ESPERA"; adb -s $dev_1  shell 'pm list packages -f' | sed -e 's/.*=//' | sed -e 's/^/ /' | sort | less; echo -e "\n\e[1;92mDone"; break;;
                            "2")  echo -e "\n\e[1;92mLista de todos los paquetes instalados en el dispositivo  : $mod_2\n"; echo -e "\e[1;92mPresiona q para salir de la vista\n"; sleep 1s | echo -e "INICIANDO DISPOSITIVO, ESPERA"; adb -s $dev_2  shell 'pm list packages -f' | sed -e 's/.*=//' | sed -e 's/^/ /' | sort | less; echo -e "\n\e[1;92mDone"; break;;
                              *) echo -e "\n\e[1;4;91mENTER THE RIGHT OPTION BRO :- (1/2)\n";;
                            esac
                        done
                    else
                        if [ "$total_dev" == "3" ]
                            then
                                echo -e "\e[93mSelecciona un dispositivo :- \e[92m\n"
                                echo -e "\e[93m1. \e[92m$dev_1 , \e[93mModel : \e[92m$mod_1"
                                echo -e "\e[93m1. \e[92m$dev_2 , \e[93mModel : \e[92m$mod_2"
                                echo -e "\e[93m1. \e[92m$dev_3 , \e[93mModel : \e[92m$mod_3"
                        while [ 1 ]; do
                            read -p $'\n\e[1;4;91mNº\e[0m\e[24;1;97m : ' options
                            case $options in
                            "1")  echo -e "\n\e[1;92mLista de todos los paquetes instalados en el dispositivo  : $mod_1\n"; echo -e "\e[1;92mPresiona q para salir de la vista\n"; sleep 1s | echo -e "INICIANDO DISPOSITIVO, ESPERA"; adb -s $dev_1  shell 'pm list packages -f' | sed -e 's/.*=//' | sed -e 's/^/ /' | sort | less; echo -e "\n\e[1;92mDone"; break;;
                            "2")  echo -e "\n\e[1;92mLista de todos los paquetes instalados en el dispositivo  : $mod_2\n"; echo -e "\e[1;92mPresiona q para salir de la vista\n"; sleep 1s | echo -e "INICIANDO DISPOSITIVO, ESPERA"; adb -s $dev_2  shell 'pm list packages -f' | sed -e 's/.*=//' | sed -e 's/^/ /' | sort | less; echo -e "\n\e[1;92mDone"; break;;
                            "3")  echo -e "\n\e[1;92mLista de todos los paquetes instalados en el dispositivo  : $mod_3\n"; echo -e "\e[1;92mPresiona q para salir de la vista\n"; sleep 1s | echo -e "INICIANDO DISPOSITIVO, ESPERA"; adb -s $dev_3  shell 'pm list packages -f' | sed -e 's/.*=//' | sed -e 's/^/ /' | sort | less; echo -e "\n\e[1;92mDone"; break;;
                              *) echo -e "\n\e[1;4;91mNº :- (1/2/3/)\n";;
                            esac
                        done
                        fi
                fi  
                        
        fi
fi

read -p $'\n\e[93;1mDESEAS LIMPIAR LA PANTALLA (clear) \e[1;97m (y/N) \e[93;1m? : \e[1;91m' yn
case $yn in
  [Yy]* ) clear; bash modulos/funcion.sh;;
  [Nn]* ) bash modulos/funcion.sh;;
  * ) bash modulos/funcion.sh;;
esac